name: Publish Jupyter Notebooks via GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nbconvert
        run: pip install nbconvert
  
      - name: Convert all ipynb files to html (and delete ipynb files)
        run: find . -name '*.ipynb' -type f -execdir jupyter nbconvert --template classic --to html --output-dir='.' {} \; -execdir rm {} \;

      - name: Push notebooks folder to the build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          FOLDER: notebooks # The directory where your assets are generated
          BRANCH: pages # The branch name where you want to push the assets
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
          SQUASH_HISTORY: true # If set to true, all previous commits on the target branch will be discarded. For example, if you are deploying a static site with lots of binary artifacts, this can help the repository becoming overly bloated.